import sqlite3
from db import db
import pandas as pd

class UserModel(db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80))
    password = db.Column(db.String(80))

    country_data = pd.read_csv('country_data.csv', usecols = ['COUNTRY', 'A2 (ISO)'])
    country_codes = list(country_data['A2 (ISO)'])

    #WARNING Indonesia ISO code ID is renamed IA

    AF = db.Column(db.String(80))
    AL = db.Column(db.String(80))
    DZ = db.Column(db.String(80))
    AS = db.Column(db.String(80))
    AD = db.Column(db.String(80))
    AO = db.Column(db.String(80))
    AI = db.Column(db.String(80))
    AQ = db.Column(db.String(80))
    AG = db.Column(db.String(80))
    AR = db.Column(db.String(80))
    AM = db.Column(db.String(80))
    AW = db.Column(db.String(80))
    AU = db.Column(db.String(80))
    AT = db.Column(db.String(80))
    AZ = db.Column(db.String(80))
    BS = db.Column(db.String(80))
    BH = db.Column(db.String(80))
    BD = db.Column(db.String(80))
    BB = db.Column(db.String(80))
    BY = db.Column(db.String(80))
    BE = db.Column(db.String(80))
    BZ = db.Column(db.String(80))
    BJ = db.Column(db.String(80))
    BM = db.Column(db.String(80))
    BT = db.Column(db.String(80))
    BO = db.Column(db.String(80))
    BQ = db.Column(db.String(80))
    BA = db.Column(db.String(80))
    BW = db.Column(db.String(80))
    BV = db.Column(db.String(80))
    BR = db.Column(db.String(80))
    IO = db.Column(db.String(80))
    BN = db.Column(db.String(80))
    BG = db.Column(db.String(80))
    BF = db.Column(db.String(80))
    BI = db.Column(db.String(80))
    KH = db.Column(db.String(80))
    CM = db.Column(db.String(80))
    CA = db.Column(db.String(80))
    CV = db.Column(db.String(80))
    KY = db.Column(db.String(80))
    CF = db.Column(db.String(80))
    TD = db.Column(db.String(80))
    CL = db.Column(db.String(80))
    CN = db.Column(db.String(80))
    CX = db.Column(db.String(80))
    CC = db.Column(db.String(80))
    CO = db.Column(db.String(80))
    KM = db.Column(db.String(80))
    CG = db.Column(db.String(80))
    CD = db.Column(db.String(80))
    CK = db.Column(db.String(80))
    CR = db.Column(db.String(80))
    HR = db.Column(db.String(80))
    CU = db.Column(db.String(80))
    CW = db.Column(db.String(80))
    CY = db.Column(db.String(80))
    CZ = db.Column(db.String(80))
    CI = db.Column(db.String(80))
    DK = db.Column(db.String(80))
    DJ = db.Column(db.String(80))
    DM = db.Column(db.String(80))
    DO = db.Column(db.String(80))
    EC = db.Column(db.String(80))
    EG = db.Column(db.String(80))
    SV = db.Column(db.String(80))
    GQ = db.Column(db.String(80))
    ER = db.Column(db.String(80))
    EE = db.Column(db.String(80))
    ET = db.Column(db.String(80))
    FK = db.Column(db.String(80))
    FO = db.Column(db.String(80))
    FJ = db.Column(db.String(80))
    FI = db.Column(db.String(80))
    FR = db.Column(db.String(80))
    GF = db.Column(db.String(80))
    PF = db.Column(db.String(80))
    TF = db.Column(db.String(80))
    GA = db.Column(db.String(80))
    GM = db.Column(db.String(80))
    GE = db.Column(db.String(80))
    DE = db.Column(db.String(80))
    GH = db.Column(db.String(80))
    GI = db.Column(db.String(80))
    GR = db.Column(db.String(80))
    GL = db.Column(db.String(80))
    GD = db.Column(db.String(80))
    GP = db.Column(db.String(80))
    GU = db.Column(db.String(80))
    GT = db.Column(db.String(80))
    GG = db.Column(db.String(80))
    GN = db.Column(db.String(80))
    GW = db.Column(db.String(80))
    GY = db.Column(db.String(80))
    HT = db.Column(db.String(80))
    HM = db.Column(db.String(80))
    VA = db.Column(db.String(80))
    HN = db.Column(db.String(80))
    HK = db.Column(db.String(80))
    HU = db.Column(db.String(80))
    IS = db.Column(db.String(80))
    IN = db.Column(db.String(80))
    IA = db.Column(db.String(80))
    IR = db.Column(db.String(80))
    IQ = db.Column(db.String(80))
    IE = db.Column(db.String(80))
    IM = db.Column(db.String(80))
    IL = db.Column(db.String(80))
    IT = db.Column(db.String(80))
    JM = db.Column(db.String(80))
    JP = db.Column(db.String(80))
    JE = db.Column(db.String(80))
    JO = db.Column(db.String(80))
    KZ = db.Column(db.String(80))
    KE = db.Column(db.String(80))
    KI = db.Column(db.String(80))
    KP = db.Column(db.String(80))
    KR = db.Column(db.String(80))
    KW = db.Column(db.String(80))
    KG = db.Column(db.String(80))
    LA = db.Column(db.String(80))
    LV = db.Column(db.String(80))
    LB = db.Column(db.String(80))
    LS = db.Column(db.String(80))
    LR = db.Column(db.String(80))
    LY = db.Column(db.String(80))
    LI = db.Column(db.String(80))
    LT = db.Column(db.String(80))
    LU = db.Column(db.String(80))
    MO = db.Column(db.String(80))
    MK = db.Column(db.String(80))
    MG = db.Column(db.String(80))
    MW = db.Column(db.String(80))
    MY = db.Column(db.String(80))
    MV = db.Column(db.String(80))
    ML = db.Column(db.String(80))
    MT = db.Column(db.String(80))
    MH = db.Column(db.String(80))
    MQ = db.Column(db.String(80))
    MR = db.Column(db.String(80))
    MU = db.Column(db.String(80))
    YT = db.Column(db.String(80))
    MX = db.Column(db.String(80))
    FM = db.Column(db.String(80))
    MD = db.Column(db.String(80))
    MC = db.Column(db.String(80))
    MN = db.Column(db.String(80))
    ME = db.Column(db.String(80))
    MS = db.Column(db.String(80))
    MA = db.Column(db.String(80))
    MZ = db.Column(db.String(80))
    MM = db.Column(db.String(80))
    NA = db.Column(db.String(80))
    NR = db.Column(db.String(80))
    NP = db.Column(db.String(80))
    NL = db.Column(db.String(80))
    NC = db.Column(db.String(80))
    NZ = db.Column(db.String(80))
    NI = db.Column(db.String(80))
    NE = db.Column(db.String(80))
    NG = db.Column(db.String(80))
    NU = db.Column(db.String(80))
    NF = db.Column(db.String(80))
    MP = db.Column(db.String(80))
    NO = db.Column(db.String(80))
    OM = db.Column(db.String(80))
    PK = db.Column(db.String(80))
    PW = db.Column(db.String(80))
    PS = db.Column(db.String(80))
    PA = db.Column(db.String(80))
    PG = db.Column(db.String(80))
    PY = db.Column(db.String(80))
    PE = db.Column(db.String(80))
    PH = db.Column(db.String(80))
    PN = db.Column(db.String(80))
    PL = db.Column(db.String(80))
    PT = db.Column(db.String(80))
    PR = db.Column(db.String(80))
    QA = db.Column(db.String(80))
    RO = db.Column(db.String(80))
    RU = db.Column(db.String(80))
    RW = db.Column(db.String(80))
    RE = db.Column(db.String(80))
    BL = db.Column(db.String(80))
    SH = db.Column(db.String(80))
    KN = db.Column(db.String(80))
    LC = db.Column(db.String(80))
    MF = db.Column(db.String(80))
    PM = db.Column(db.String(80))
    VC = db.Column(db.String(80))
    WS = db.Column(db.String(80))
    SM = db.Column(db.String(80))
    ST = db.Column(db.String(80))
    SA = db.Column(db.String(80))
    SN = db.Column(db.String(80))
    RS = db.Column(db.String(80))
    SC = db.Column(db.String(80))
    SL = db.Column(db.String(80))
    SG = db.Column(db.String(80))
    SX = db.Column(db.String(80))
    SK = db.Column(db.String(80))
    SI = db.Column(db.String(80))
    SB = db.Column(db.String(80))
    SO = db.Column(db.String(80))
    ZA = db.Column(db.String(80))
    GS = db.Column(db.String(80))
    SS = db.Column(db.String(80))
    ES = db.Column(db.String(80))
    LK = db.Column(db.String(80))
    SD = db.Column(db.String(80))
    SR = db.Column(db.String(80))
    SJ = db.Column(db.String(80))
    SZ = db.Column(db.String(80))
    SE = db.Column(db.String(80))
    CH = db.Column(db.String(80))
    SY = db.Column(db.String(80))
    TW = db.Column(db.String(80))
    TJ = db.Column(db.String(80))
    TZ = db.Column(db.String(80))
    TH = db.Column(db.String(80))
    TL = db.Column(db.String(80))
    TG = db.Column(db.String(80))
    TK = db.Column(db.String(80))
    TO = db.Column(db.String(80))
    TT = db.Column(db.String(80))
    TN = db.Column(db.String(80))
    TR = db.Column(db.String(80))
    TM = db.Column(db.String(80))
    TC = db.Column(db.String(80))
    TV = db.Column(db.String(80))
    UG = db.Column(db.String(80))
    UA = db.Column(db.String(80))
    AE = db.Column(db.String(80))
    GB = db.Column(db.String(80))
    US = db.Column(db.String(80))
    UM = db.Column(db.String(80))
    UY = db.Column(db.String(80))
    UZ = db.Column(db.String(80))
    VU = db.Column(db.String(80))
    VE = db.Column(db.String(80))
    VN = db.Column(db.String(80))
    VG = db.Column(db.String(80))
    VI = db.Column(db.String(80))
    WF = db.Column(db.String(80))
    EH = db.Column(db.String(80))
    YE = db.Column(db.String(80))
    ZM = db.Column(db.String(80))
    ZW = db.Column(db.String(80))


    def __init__(self, username, password,):
        self.username = username
        self.password = password

    def save_to_db(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def find_by_username(cls, username):
        return cls.query.filter_by(username=username).first()

    @classmethod
    def find_by_id(cls, _id):
        return cls.query.filter_by(id=_id).first()
    
    @classmethod
    def find_all_countries(cls, username):
        return cls.query.filter_by(id=_id).first()
